import "../globals.css";
import type { Metadata } from "next";
import Image from "next/image";
import Logo from "../../public/images/logo.svg";
import SearchIcon from "../../public/icons/search.svg";
import UserIcon from "../../public/icons/user.svg";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="bg-gray">
        <div className="w-screen min-h-full">
          <div className="mx-auto py-8 w-[1320px]">
            <nav className="bg-white p-8 mb-6 rounded-3xl w-full flex items-center">
              <div className="flex-1">
                <span className="font-head mr-10">New Drops 🔥</span>
                <span className="font-head mr-10">Men ▾</span>
                <span className="font-head mr-10">Women ▾</span>
              </div>
              <Link href="/" className="mx-auto flex-1 flex justify-center">
                <h1 className="w-px h-px overflow-hidden absolute">Kicks</h1>
                <Image src={Logo} alt="Kicks"></Image>
              </Link>
              <div className="flex-1 flex justify-end items-center">
                <span className="ml-10">
                  <h2 className="w-px h-px absolute overflow-hidden">Search</h2>
                  <Image src={SearchIcon} alt="search"></Image>
                </span>
                <span className="ml-10">
                  <h2 className="w-px h-px absolute overflow-hidden">User</h2>
                  <Image src={UserIcon} alt="user"></Image>
                </span>
                <span className="bg-orange rounded-full w-8 h-8 ml-10 flex justify-center items-center">
                  0
                </span>
              </div>
            </nav>
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
